site_name: My Docs
site_url: https://phenomenoner.github.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
  language: zh-TW
plugins:
  - blog